sudo: false

language: php

branches:
  except:
    - /^release-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

php:
 - 7.1
 - 7.2

env:
  global:
    - EXECUTE_CS_CHECK=false
    - TEST_COVERAGE=false
  matrix:
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - DEPENDENCIES=""

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: DEPENDENCIES="" EXECUTE_CS_CHECK=true TEST_COVERAGE=true
  exclude:
    - php: 7.2
      env: DEPENDENCIES=""

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --no-update satooshi/php-coveralls:dev-master ; fi

install:
  - travis_retry composer update --no-interaction --prefer-dist $DEPENDENCIES
  - composer info -i

before_script:
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then mkdir -p "$HOME/.php-cs-fixer" ; fi

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml; else ./vendor/bin/phpunit; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi

